import source from '../jabodetabek_transit_data (1).json'

export type Mode = 'KRL' | 'MRT' | 'LRT_JABODEBEK' | 'LRT_JAKARTA' | 'TRANSJAKARTA'
export type EntryType = 'place' | 'stop' | 'service'
export interface CanonicalPlace { id: string; name: string; aliases: string[]; modes: Mode[]; category: 'hub' | 'place' }
export interface ServiceStop { id: string; placeId: string; serviceId: string; sourceCode: string; label: string; sequence: number }
export interface Service { id: string; mode: Mode; name: string; color: string; route: string; stops: ServiceStop[]; branchRules?: string[]; variants: string[] }
export interface TransferEdge { fromStopId: string; toStopId: string; type: 'in_station' | 'short_walk'; confidence: 'verified'; note: string }
export interface EncyclopediaEntry { type: EntryType; id: string; title: string; subtitle: string; searchTokens: string[] }
export type LessonQuizKind = 'choice' | 'true_false' | 'sequence' | 'map_select'
export interface LessonQuiz { question: string; choices: string[]; answerIndex: number; explanation: string; kind?: LessonQuizKind; correctSequence?: string[]; targetLabel?: string }
export interface LessonPractice { prompt: string; options: string[]; answerIndex: number; success: string }
export interface Lesson { id: string; unitId: number; title: string; concept: string; objective: string; facts: string[]; focusServiceIds: string[]; focusPlaceId?: string; quizIds: string[]; quizzes: LessonQuiz[]; practice: LessonPractice; practiceChallengeId: string; unlockRule: string }
export interface PipeMapNode { stopId: string; x: number; y: number; labelLevel: 'full' | 'compact' | 'hidden'; isTerminus: boolean; isTransfer: boolean }
export interface PipeMapLayout { serviceId: string; orientation: 'vertical'; nodePositions: PipeMapNode[]; branchPositions?: Array<{ fromStopId: string; nodes: Array<{ id: string; label: string; x: number; y: number }> }> }
export interface HubMap { placeId: string; services: Service[]; transferEdges: TransferEdge[]; legend: Array<{ serviceId: string; name: string; color: string }> }

type RawStop = { code: string; name: string }
type RawService = { id: string; mode: Mode; name?: string; route?: string; color: string; stations: RawStop[]; branches?: { from_code: string; to: RawStop[] }[] }
const rawServices = [...source.lines, ...source.transjakarta_corridors] as RawService[]
const slug = (value: string) => value.toLocaleLowerCase('id').normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')
const aliasMap: Record<string, { id: string; name: string; aliases: string[]; category: 'hub' | 'place' }> = {
  'jakarta-kota': { id: 'kota', name: 'Kota (Jakarta Kota)', aliases: ['Kota', 'Jakarta Kota'], category: 'hub' },
  kota: { id: 'kota', name: 'Kota (Jakarta Kota)', aliases: ['Kota', 'Jakarta Kota'], category: 'hub' },
  'dukuh-atas-bni': { id: 'dukuh-atas', name: 'Dukuh Atas', aliases: ['Dukuh Atas', 'Dukuh Atas BNI', 'Dukuh Atas/Galunggung'], category: 'hub' },
  'dukuh-atas-galunggung': { id: 'dukuh-atas', name: 'Dukuh Atas', aliases: ['Dukuh Atas', 'Dukuh Atas BNI', 'Dukuh Atas/Galunggung'], category: 'hub' },
  manggarai: { id: 'manggarai', name: 'Manggarai', aliases: ['Manggarai'], category: 'hub' }, cawang: { id: 'cawang', name: 'Cawang', aliases: ['Cawang'], category: 'hub' }, duri: { id: 'duri', name: 'Duri', aliases: ['Duri'], category: 'hub' }, jatinegara: { id: 'jatinegara', name: 'Jatinegara', aliases: ['Jatinegara'], category: 'hub' }, 'kampung-bandan': { id: 'kampung-bandan', name: 'Kampung Bandan', aliases: ['Kampung Bandan'], category: 'hub' }, 'batu-ceper': { id: 'batu-ceper', name: 'Batu Ceper', aliases: ['Batu Ceper'], category: 'hub' }, grogol: { id: 'grogol', name: 'Grogol', aliases: ['Grogol'], category: 'hub' }, 'kampung-melayu': { id: 'kampung-melayu', name: 'Kampung Melayu', aliases: ['Kampung Melayu'], category: 'hub' },
}
const placeByKey = new Map<string, CanonicalPlace>()
const getPlace = (label: string, mode: Mode): CanonicalPlace => {
  const key = slug(label); const mapped = aliasMap[key]; const id = mapped?.id ?? `place-${key}`
  const existing = placeByKey.get(id)
  if (existing) { if (!existing.modes.includes(mode)) existing.modes.push(mode); if (!existing.aliases.includes(label)) existing.aliases.push(label); return existing }
  const place: CanonicalPlace = { id, name: mapped?.name ?? label, aliases: [...new Set([label, ...(mapped?.aliases ?? [])])], modes: [mode], category: mapped?.category ?? 'place' }
  placeByKey.set(id, place); return place
}
export const services: Service[] = rawServices.map((raw) => ({ id: raw.id, mode: raw.mode, name: raw.name ?? `TransJakarta Koridor ${raw.id.replace('TJ_', '')}`, color: raw.color, route: raw.route ?? raw.name ?? '', stops: raw.stations.map((station, sequence) => ({ id: `${raw.id}:${station.code}`, placeId: getPlace(station.name, raw.mode).id, serviceId: raw.id, sourceCode: station.code, label: station.name, sequence })), branchRules: raw.branches?.map((branch) => `${branch.from_code} → ${branch.to.map((stop) => stop.name).join(', ')}`), variants: (source.transjakarta_variants ?? []).filter((variant) => `TJ_${variant.base_corridor}` === raw.id).map((variant) => `${variant.id}: ${variant.route}`) }))
export const places = [...placeByKey.values()].sort((a, b) => a.name.localeCompare(b.name, 'id'))
export const stops = services.flatMap((service) => service.stops)
const stopId = (serviceId: string, code: string) => `${serviceId}:${code}`
export const transferEdges: TransferEdge[] = [
  { fromStopId: stopId('LRT_JBDBK_BEKASI', 'BK01'), toStopId: stopId('MRT_NS', 'M12'), type: 'short_walk', confidence: 'verified', note: 'Dukuh Atas: LRT Jabodebek ke MRT.' },
  { fromStopId: stopId('LRT_JBDBK_CIBUBUR', 'CB01'), toStopId: stopId('MRT_NS', 'M12'), type: 'short_walk', confidence: 'verified', note: 'Dukuh Atas: LRT Jabodebek ke MRT.' },
  { fromStopId: stopId('KRL_BOGOR', 'B07'), toStopId: stopId('KRL_CIKARANG_LOOP', 'C01'), type: 'in_station', confidence: 'verified', note: 'Manggarai: koneksi KRL.' },
  { fromStopId: stopId('KRL_BOGOR', 'B07'), toStopId: stopId('KRL_AIRPORT', 'A01'), type: 'in_station', confidence: 'verified', note: 'Manggarai: koneksi Airport Rail Link.' },
  { fromStopId: stopId('KRL_TANGERANG', 'T01'), toStopId: stopId('KRL_AIRPORT', 'A03'), type: 'in_station', confidence: 'verified', note: 'Duri: koneksi KRL Tangerang dan Airport Rail Link.' },
  { fromStopId: stopId('KRL_TANGERANG', 'T09'), toStopId: stopId('KRL_AIRPORT', 'A03a'), type: 'in_station', confidence: 'verified', note: 'Batu Ceper: koneksi KRL Tangerang dan Airport Rail Link.' },
]
const branchSource = new Map(rawServices.filter((service) => service.branches).map((service) => [service.id, service.branches ?? []]))
export const pipeMapLayout = (serviceId: string): PipeMapLayout | undefined => {
  const service = services.find((item) => item.id === serviceId)
  if (!service) return undefined
  const nodePositions = service.stops.map((stop) => ({ stopId: stop.id, x: 160, y: 44 + stop.sequence * 62, labelLevel: 'full' as const, isTerminus: stop.sequence === 0 || stop.sequence === service.stops.length - 1, isTransfer: transferEdges.some((edge) => edge.fromStopId === stop.id || edge.toStopId === stop.id) }))
  const branches = branchSource.get(serviceId)
  const branchPositions = branches?.flatMap((branch) => {
    const parent = service.stops.find((stop) => stop.sourceCode === branch.from_code)
    const parentNode = nodePositions.find((node) => node.stopId === parent?.id)
    if (!parent || !parentNode) return []
    return [{ fromStopId: parent.id, nodes: branch.to.map((stop, index) => ({ id: `${serviceId}:branch:${stop.code}`, label: stop.name, x: 250 + index * 42, y: parentNode.y + 48 + index * 40 })) }]
  })
  return { serviceId, orientation: 'vertical', nodePositions, branchPositions }
}
export const majorHubIds = ['dukuh-atas', 'manggarai', 'cawang', 'jatinegara', 'kota', 'duri', 'batu-ceper', 'kampung-bandan', 'grogol', 'kampung-melayu']
export const hubMap = (placeId: string): HubMap | undefined => {
  const place = places.find((item) => item.id === placeId)
  if (!place || place.category !== 'hub') return undefined
  const placeStops = stops.filter((stop) => stop.placeId === placeId)
  const serviceIds = [...new Set(placeStops.map((stop) => stop.serviceId))]
  const hubTransfers = transferEdges.filter((edge) => [edge.fromStopId, edge.toStopId].every((id) => placeStops.some((stop) => stop.id === id)))
  const hubServices = services.filter((service) => serviceIds.includes(service.id))
  return { placeId, services: hubServices, transferEdges: hubTransfers, legend: hubServices.map((service) => ({ serviceId: service.id, name: service.name, color: service.color })) }
}
export const entries: EncyclopediaEntry[] = [
  ...places.map((place) => ({ type: 'place' as const, id: place.id, title: place.name, subtitle: `${place.modes.length} moda • ${place.category === 'hub' ? 'hub' : 'tempat'}`, searchTokens: [place.name, ...place.aliases, ...place.modes] })),
  ...services.map((service) => ({ type: 'service' as const, id: service.id, title: service.name, subtitle: service.route || `${service.stops.length} stop`, searchTokens: [service.name, service.route, service.id, service.mode] })),
  ...stops.map((stop) => ({ type: 'stop' as const, id: stop.id, title: stop.label, subtitle: services.find((service) => service.id === stop.serviceId)?.name ?? stop.serviceId, searchTokens: [stop.label, stop.sourceCode] })),
]
const buildLesson = (unitId: number, index: number, title: string, objective: string, facts: string[], focusServiceIds: string[], quizzes: LessonQuiz[], practice: LessonPractice, focusPlaceId?: string): Lesson => ({ id: `u${unitId}-l${index}`, unitId, title, concept: title, objective, facts, focusServiceIds, focusPlaceId, quizzes, practice, quizIds: [`${unitId}.${index}.a`, `${unitId}.${index}.b`], practiceChallengeId: index === 5 ? `mastery-u${unitId}` : `practice-u${unitId}-l${index}`, unlockRule: unitId === 1 ? 'Mulai tersedia' : `Selesaikan Unit ${unitId - 1}` })
const quiz = (question: string, choices: string[], answerIndex: number, explanation: string): LessonQuiz => ({ question, choices, answerIndex, explanation })
const practice = (prompt: string, options: string[], answerIndex: number, success: string): LessonPractice => ({ prompt, options, answerIndex, success })
export const lessons: Lesson[] = [
  buildLesson(1, 1, 'Moda dan warna jalur', 'Kenali bahwa warna selalu perlu dibaca bersama nama layanan.', ['MRT, LRT, dan KRL adalah layanan rel yang berbeda.', 'Warna membantu mengikuti satu jalur pada peta skematik.'], ['MRT_NS','LRT_JBDBK_BEKASI','KRL_BOGOR'], [quiz('Moda apakah yang melayani Dukuh Atas BNI pada peta ini?', ['MRT Jakarta','KRL Bogor','Airport Rail Link'], 0, 'Dukuh Atas BNI tercatat sebagai stop MRT North-South Line.'), quiz('Apa fungsi utama warna jalur?', ['Menunjukkan urutan layanan','Menunjukkan tarif','Menentukan jadwal'], 0, 'Pada peta skematik, warna membedakan jalur agar urutannya mudah diikuti.')], practice('Pilih layanan MRT pada legenda.', ['MRT North-South Line','Bogor Line','LRT Bekasi Line'], 0, 'Benar. Selalu baca nama dan warna layanan bersama-sama.')),
  buildLesson(1, 2, 'Terminal dan arah perjalanan', 'Gunakan dua ujung PipeMap untuk memahami arah layanan.', ['Terminus adalah stop pertama atau terakhir dalam urutan layanan.', 'MRT North-South Line menghubungkan Lebak Bulus Grab dan Bundaran HI Bank Jakarta.'], ['MRT_NS'], [quiz('Terminus selatan MRT North-South Line adalah…', ['Lebak Bulus Grab','Dukuh Atas BNI','Bundaran HI Bank Jakarta'], 0, 'Lebak Bulus Grab adalah stop pertama pada data MRT.'), quiz('Jika bergerak dari Blok M ke arah pusat, stop MRT berikutnya adalah…', ['ASEAN','Fatmawati','Lebak Bulus Grab'], 0, 'Pada urutan data, ASEAN berada setelah Blok M BCA menuju Bundaran HI.')], practice('Pilih terminus MRT pada sisi utara.', ['Bundaran HI Bank Jakarta','Senayan Mastercard','Blok M BCA'], 0, 'Tepat. Terminus membantu memilih arah perjalanan.')),
  buildLesson(1, 3, 'Urutan stop pada jalur', 'Baca stop satu per satu tanpa melompati urutan PipeMap.', ['Setiap stop memiliki nomor urut pada layanan.', 'Stop sebelum dan sesudahnya menentukan konteks perjalanan.'], ['MRT_NS'], [quiz('Stop tepat setelah ASEAN menuju Bundaran HI adalah…', ['Senayan Mastercard','Blok M BCA','Cipete Raya'], 0, 'Urutan MRT dari Blok M menuju utara melewati ASEAN lalu Senayan Mastercard.'), quiz('Mengapa nomor urut stop berguna?', ['Membaca posisi dan arah','Menghitung tarif','Memeriksa jadwal langsung'], 0, 'Nomor urut menjelaskan posisi stop dalam satu layanan.')], practice('Dari ASEAN, pilih stop MRT berikutnya menuju Bundaran HI.', ['Senayan Mastercard','Haji Nawi','Lebak Bulus Grab'], 0, 'Benar. Kamu mengikuti urutan PipeMap, bukan menebak dari nama.')),
  buildLesson(1, 4, 'Apa itu transfer', 'Bedakan transfer yang terverifikasi dari nama stop yang kebetulan sama.', ['Transfer hanya ditampilkan jika ada edge yang dikurasi.', 'Dukuh Atas memiliki transfer jalan kaki singkat antara LRT Jabodebek dan MRT.'], ['LRT_JBDBK_BEKASI','MRT_NS'], [quiz('Transfer LRT Jabodebek ke MRT pada data berada di…', ['Dukuh Atas','Blok M','Jatinegara'], 0, 'Transfer terverifikasi LRT Jabodebek–MRT ada di Dukuh Atas.'), quiz('Dua nama stop yang sama otomatis berarti transfer?', ['Tidak, harus ada koneksi terverifikasi','Ya, selalu','Hanya untuk KRL'], 0, 'Commutopia tidak membuat transfer hanya dari kecocokan nama.')], practice('Pilih transfer yang diverifikasi.', ['LRT Jabodebek Dukuh Atas → MRT Dukuh Atas','KRL Bogor → MRT Blok M','LRT Jakarta → KRL Kota'], 0, 'Tepat. Ini adalah transfer jalan kaki singkat yang dikurasi.')),
  buildLesson(1, 5, 'Membaca peta skematik', 'Gunakan warna, node, dan arah untuk membaca hubungan tanpa menganggap peta geografis.', ['PipeMap menunjukkan urutan jaringan, bukan lokasi jalan yang presisi.', 'Node transfer diberi ring agar mudah dikenali.'], ['LRT_JBDBK_BEKASI','MRT_NS'], [quiz('PipeMap adalah peta…', ['Skematik urutan layanan','Navigasi jalan real-time','Tarif perjalanan'], 0, 'PipeMap menyederhanakan jaringan agar pola koneksi mudah dipelajari.'), quiz('Apa arti node dengan ring transfer?', ['Ada koneksi terverifikasi','Stop sedang tutup','Terminus layanan'], 0, 'Ring menandai stop yang memiliki koneksi transfer dalam scope data.')], practice('Pilih node yang menjadi titik transfer LRT–MRT.', ['Dukuh Atas','Bekasi Barat','Blok A'], 0, 'Benar. Dukuh Atas adalah node transfer pada peta ini.')),
  buildLesson(2, 1, 'Lin Bogor dan koridor inti', 'Kenali spine KRL Bogor dari Jakarta Kota hingga Bogor.', ['Bogor Line berawal di Jakarta Kota pada data sumber.', 'Manggarai berada pada Bogor Line sebagai hub penting.'], ['KRL_BOGOR'], [quiz('Terminus Jakarta pada Bogor Line adalah…', ['Jakarta Kota','Manggarai','Duri'], 0, 'Jakarta Kota adalah stop B01 pada Bogor Line.'), quiz('Hub KRL mana berada pada Bogor Line?', ['Manggarai','Blok M','Halim'], 0, 'Manggarai adalah stop B07 dan memiliki transfer KRL terverifikasi.')], practice('Pilih arah Bogor Line dari Manggarai menuju pusat kota.', ['Jakarta Kota','Bogor','Bandara'], 0, 'Tepat. Jakarta Kota berada di sisi pusat kota pada PipeMap.')),
  buildLesson(2, 2, 'Lin Lingkar Cikarang', 'Ikuti Cikarang Loop dari Manggarai ke arah Jatinegara dan koridor timur.', ['Cikarang Loop mencantumkan Manggarai dan Jatinegara.', 'Jatinegara berada setelah Matraman dari arah Manggarai.'], ['KRL_CIKARANG_LOOP'], [quiz('Dari Manggarai, stop Cikarang Loop berikutnya adalah…', ['Matraman','Jatinegara','Jakarta Kota'], 0, 'Data menempatkan Matraman tepat setelah Manggarai.'), quiz('Jatinegara dilayani oleh…', ['KRL Cikarang Loop','MRT North-South','LRT Jakarta Southern'], 0, 'Jatinegara ada pada Cikarang Loop di data KRL.')], practice('Pilih stop setelah Matraman menuju timur.', ['Jatinegara','Manggarai','Duri'], 0, 'Benar. Kamu mengikuti urutan Manggarai → Matraman → Jatinegara.')),
  buildLesson(2, 3, 'Manggarai sebagai hub KRL', 'Gunakan Manggarai untuk berpindah dari Cikarang Loop ke Bogor Line.', ['Manggarai memiliki transfer dalam area stasiun antara Bogor Line dan Cikarang Loop.', 'Manggarai juga terhubung ke Airport Rail Link dalam scope data.'], ['KRL_BOGOR','KRL_CIKARANG_LOOP','KRL_AIRPORT'], [quiz('Transfer KRL yang diverifikasi di Manggarai adalah…', ['Bogor Line ↔ Cikarang Loop','MRT ↔ LRT Jakarta','TJ 1 ↔ MRT'], 0, 'Manggarai adalah koneksi dalam area stasiun untuk dua layanan KRL tersebut.'), quiz('Layanan lain yang terhubung ke Manggarai di data adalah…', ['Airport Rail Link','LRT Jakarta Southern','MRT North-South'], 0, 'Airport Rail Link memiliki stop Manggarai dan edge transfer terverifikasi.')], practice('Dari Cikarang Loop di Manggarai, pilih layanan untuk menuju Kota.', ['Bogor Line','Airport Rail Link','MRT North-South'], 0, 'Tepat. Bogor Line membawa perjalanan ke Jakarta Kota.')),
  buildLesson(2, 4, 'Jatinegara, Duri, Batu Ceper', 'Kenali tiga stop KRL sebagai konteks arah dan koneksi.', ['Jatinegara berada pada Cikarang Loop.', 'Duri dan Batu Ceper memiliki koneksi KRL Tangerang–Airport Rail Link yang terverifikasi.'], ['KRL_CIKARANG_LOOP','KRL_TANGERANG','KRL_AIRPORT'], [quiz('Koneksi Airport Rail Link yang terverifikasi di Duri terhubung dengan…', ['KRL Tangerang','MRT','LRT Bekasi'], 0, 'Duri memiliki transfer dalam area stasiun KRL Tangerang–Airport Rail Link.'), quiz('Jatinegara ada pada jalur…', ['Cikarang Loop','Bogor Line','Tangerang Line'], 0, 'Jatinegara adalah bagian dari Cikarang Loop.')], practice('Pilih stop yang memiliki transfer KRL Tangerang–Airport Rail Link.', ['Duri','Blok M','Cawang'], 0, 'Benar. Duri adalah salah satu koneksi terverifikasi.')),
  buildLesson(2, 5, 'Tantangan pengenalan KRL', 'Gabungkan arah, urutan stop, dan transfer KRL.', ['Jatinegara → Manggarai menggunakan Cikarang Loop.', 'Manggarai → Jakarta Kota menggunakan Bogor Line.'], ['KRL_CIKARANG_LOOP','KRL_BOGOR'], [quiz('Untuk perjalanan Jatinegara ke Kota, hub transfernya adalah…', ['Manggarai','Duri','Cawang'], 0, 'Manggarai menghubungkan Cikarang Loop dan Bogor Line.'), quiz('Setelah transfer di Manggarai, jalur menuju Kota adalah…', ['Bogor Line','Airport Rail Link','Tangerang Line'], 0, 'Bogor Line memiliki terminus Jakarta Kota.')], practice('Susun langkah setelah Jatinegara.', ['Cikarang Loop → Manggarai → Bogor Line → Kota','Bogor Line → Blok M → Kota','Airport Rail Link → Bandara → Kota'], 0, 'Mantap. Kamu sudah mengenali pola transfer KRL di Manggarai.')),
  buildLesson(3, 1, 'MRT Lin Utara–Selatan', 'Baca koridor MRT dari Lebak Bulus ke Bundaran HI.', ['MRT North-South Line memiliki 13 stop pada dataset.', 'Dukuh Atas BNI berada dekat sisi Bundaran HI dibanding Lebak Bulus.'], ['MRT_NS'], [quiz('MRT North-South Line memiliki terminus utara…', ['Bundaran HI Bank Jakarta','Lebak Bulus Grab','Blok M BCA'], 0, 'Bundaran HI Bank Jakarta adalah stop terakhir pada data.'), quiz('Stop MRT sebelum Dukuh Atas dari arah Lebak Bulus adalah…', ['Setiabudi Astra','Bundaran HI','ASEAN'], 0, 'Urutan data menempatkan Setiabudi Astra sebelum Dukuh Atas BNI.')], practice('Pilih arah MRT dari Dukuh Atas menuju Blok M.', ['Lebak Bulus Grab','Bundaran HI Bank Jakarta','Jakarta Kota'], 0, 'Benar. Blok M berada ke arah Lebak Bulus dari Dukuh Atas.')),
  buildLesson(3, 2, 'LRT Jakarta Lin Selatan', 'Kenali LRT Jakarta sebagai layanan tersendiri dengan urutan enam stop.', ['LRT Jakarta Southern Line menghubungkan Pegangsaan Dua dan Velodrome.', 'LRT Jakarta berbeda dari LRT Jabodebek.'], ['LRT_JKT_SOUTH'], [quiz('Terminus LRT Jakarta Southern Line adalah…', ['Pegangsaan Dua dan Velodrome','Dukuh Atas dan Bekasi','Lebak Bulus dan Bundaran HI'], 0, 'Data LRT Jakarta Southern mencantumkan Pegangsaan Dua hingga Velodrome.'), quiz('Jumlah stop pada LRT Jakarta Southern Line adalah…', ['6','13','14'], 0, 'Dataset mencantumkan enam stop.')], practice('Pilih terminus LRT Jakarta.', ['Velodrome','Cawang','Manggarai'], 0, 'Tepat. Velodrome adalah salah satu terminus LRT Jakarta.')),
  buildLesson(3, 3, 'Trunk LRT Jabodebek', 'Kenali trunk bersama LRT Jabodebek sebelum cabang Bekasi dan Cibubur berpisah.', ['Bekasi dan Cibubur Line sama-sama melewati Dukuh Atas dan Cawang.', 'Dua layanan ini memiliki transfer jalan kaki singkat ke MRT di Dukuh Atas.'], ['LRT_JBDBK_BEKASI','LRT_JBDBK_CIBUBUR','MRT_NS'], [quiz('Stop trunk yang dilalui dua cabang LRT Jabodebek adalah…', ['Cawang','Velodrome','Batu Ceper'], 0, 'Kedua layanan LRT Jabodebek sama-sama mencantumkan Cawang.'), quiz('Transfer LRT Jabodebek ke MRT tersedia di…', ['Dukuh Atas','Kota','Jatinegara'], 0, 'Dukuh Atas adalah transfer terverifikasi ke MRT.')], practice('Pilih stop trunk yang menjadi transfer ke MRT.', ['Dukuh Atas BNI','Halim','Harjamukti'], 0, 'Benar. Dari Dukuh Atas, kamu bisa berpindah ke MRT.')),
  buildLesson(3, 4, 'Cabang Bekasi vs Cibubur', 'Bedakan ujung jalur setelah trunk LRT Jabodebek.', ['Bekasi Line berlanjut dari Cawang ke Halim dan Jati Mulya.', 'Cibubur Line berlanjut dari Cawang ke TMII dan Harjamukti.'], ['LRT_JBDBK_BEKASI','LRT_JBDBK_CIBUBUR'], [quiz('Setelah Cawang pada Bekasi Line, stop berikutnya adalah…', ['Halim','TMII','Harjamukti'], 0, 'Bekasi Line bergerak dari Cawang ke Halim.'), quiz('Terminus Cibubur Line adalah…', ['Harjamukti','Jati Mulya','Bekasi Barat'], 0, 'Harjamukti adalah stop terakhir pada Cibubur Line.')], practice('Pilih cabang untuk menuju Harjamukti.', ['LRT Jabodebek Cibubur Line','LRT Jabodebek Bekasi Line','MRT North-South Line'], 0, 'Tepat. Harjamukti berada di ujung Cibubur Line.')),
  buildLesson(3, 5, 'Tantangan Dukuh Atas dan Cawang', 'Pilih hub yang tepat untuk perpindahan MRT atau cabang LRT.', ['Dukuh Atas adalah transfer LRT Jabodebek–MRT yang diverifikasi.', 'Cawang adalah titik trunk sebelum cabang Bekasi dan Cibubur berbeda.'], ['LRT_JBDBK_BEKASI','LRT_JBDBK_CIBUBUR','MRT_NS'], [quiz('Untuk berpindah LRT Jabodebek ke MRT, pilih…', ['Dukuh Atas','Cawang','Halim'], 0, 'Dukuh Atas memiliki edge transfer LRT Jabodebek–MRT.'), quiz('Untuk membedakan perjalanan ke Bekasi atau Cibubur, perhatikan…', ['Cabang setelah Cawang','Warna saja','Nama Kota saja'], 0, 'Setelah Cawang, urutan stop menentukan cabang tujuan.')], practice('Pilih rantai menuju Blok M dari Dukuh Atas.', ['LRT Jabodebek → transfer Dukuh Atas → MRT arah Lebak Bulus','LRT Jakarta → Cawang → MRT','KRL Bogor → Kota → MRT'], 0, 'Hebat. Kamu sudah menggabungkan hub, transfer, dan arah layanan.')),
]
const enrichQuiz = (lessonId: string, quizIndex: number, update: Partial<LessonQuiz>) => Object.assign(lessons.find((lesson) => lesson.id === lessonId)!.quizzes[quizIndex], update)

// Tambahan variasi interaksi, tetap memakai fakta dan stop dari katalog yang sama.
enrichQuiz('u1-l1', 1, { kind: 'true_false', question: 'Benar atau salah: warna jalur membantu membaca urutan layanan pada peta skematik.', choices: ['Benar', 'Salah'], answerIndex: 0 })
enrichQuiz('u1-l2', 0, { kind: 'map_select', question: 'Tap terminus selatan pada mini PipeMap MRT.', choices: ['Lebak Bulus Grab', 'Blok M BCA', 'Bundaran HI Bank Jakarta'], answerIndex: 0, targetLabel: 'Lebak Bulus Grab' })
enrichQuiz('u1-l3', 0, { kind: 'sequence', question: 'Susun tiga stop MRT ini dari ASEAN menuju Bundaran HI.', choices: ['ASEAN', 'Senayan Mastercard', 'Istora Mandiri'], answerIndex: 0, correctSequence: ['ASEAN', 'Senayan Mastercard', 'Istora Mandiri'] })
enrichQuiz('u1-l4', 1, { kind: 'true_false', question: 'Benar atau salah: dua stop dengan nama sama otomatis menjadi transfer.', choices: ['Benar', 'Salah'], answerIndex: 1 })
enrichQuiz('u2-l1', 1, { kind: 'map_select', question: 'Tap node hub KRL pada mini PipeMap Bogor Line.', choices: ['Jakarta Kota', 'Manggarai', 'Bogor'], answerIndex: 1, targetLabel: 'Manggarai' })
enrichQuiz('u2-l2', 0, { kind: 'sequence', question: 'Susun perjalanan Cikarang Loop dari Manggarai menuju Jatinegara.', choices: ['Manggarai', 'Matraman', 'Jatinegara'], answerIndex: 0, correctSequence: ['Manggarai', 'Matraman', 'Jatinegara'] })
enrichQuiz('u2-l3', 0, { kind: 'true_false', question: 'Benar atau salah: Manggarai memiliki transfer KRL terverifikasi antara Bogor Line dan Cikarang Loop.', choices: ['Benar', 'Salah'], answerIndex: 0 })
enrichQuiz('u3-l2', 1, { kind: 'true_false', question: 'Benar atau salah: LRT Jakarta Southern Line memiliki enam stop pada dataset.', choices: ['Benar', 'Salah'], answerIndex: 0 })
enrichQuiz('u3-l4', 0, { kind: 'sequence', question: 'Susun cabang Bekasi setelah Cawang.', choices: ['Cawang', 'Halim', 'Jati Mulya'], answerIndex: 0, correctSequence: ['Cawang', 'Halim', 'Jati Mulya'] })
enrichQuiz('u3-l5', 0, { kind: 'map_select', question: 'Tap titik transfer LRT Jabodebek ke MRT.', choices: ['Cawang', 'Dukuh Atas BNI', 'Halim'], answerIndex: 1, targetLabel: 'Dukuh Atas BNI' })
export const modeLabels: Record<Mode, string> = { KRL: 'KRL', MRT: 'MRT Jakarta', LRT_JABODEBEK: 'LRT Jabodebek', LRT_JAKARTA: 'LRT Jakarta', TRANSJAKARTA: 'TransJakarta' }
export const catalogStats = { services: services.length, stops: stops.length, places: places.length, hubs: places.filter((place) => place.category === 'hub').length }
