import { StrictMode, useEffect, useState, type CSSProperties } from 'react'
import { createRoot } from 'react-dom/client'
import { challenges, dataAudit, edges, mentorCopy, mentorFor, nodes, places, type Challenge } from './domain'
import { actionsForStation, canReachScenarioGoal, chainScenarios, lineTone, type ChainAction, type ChainRunSummary, type ChainScenario } from './chain-engine'
import { claimChainScenarioReward, claimPipeRushReward, defaultProfile, demoProfile, readProfile, resetProfile, writeProfile, type Profile } from './storage'
import { Explore, LearningPath } from './explore'
import { Atlas, AtlasRoutePractice } from './atlas'
import { TransitMentorCard } from './mentor'
import { transitGraph, type RoutePracticeScenario } from './transit-graph'
import { ChainReactionGame as ReferenceChainReactionGame } from './chain-reaction'
import { PipeRushGame } from './pipe-rush'
import type { PipeRushRunSummary } from './pipe-rush-engine'
import './styles.css'
import './polish.css'
import './explore.css'
import './quiz.css'
import './upcoming.css'
import './refine.css'
import './explore-polish.css'
import './learning.css'
import './atlas.css'
import './atlas-polish.css'
import './mentor.css'
import './chain-reaction.css'
import './chain-reaction-compact.css'
import './pipe-rush.css'
import './pipe-rush-result.css'
import './pipe-rush-variations.css'
import './game-hub.css'
import './game-hub-grid.css'

type Screen = 'welcome' | 'learn' | 'explore' | 'atlas' | 'atlas-practice' | 'lesson' | 'main' | 'game' | 'result' | 'progress' | 'inspector'
const icons = { train: '▣', star: '✦', fire: '♨', arrow: '→', check: '✓', lock: '▣', map: '⌘' }

function Mascot({ small = false }: { small?: boolean }) { return <div className={`mascot ${small ? 'small' : ''}`} role="img" aria-label="Commu, mentor transit"><span className="cap">C</span><span className="mascot-ear left"/><span className="mascot-ear right"/><span className="face"><i className="eye left"/><i className="eye right"/><i className="smile"/></span><span className="antenna"/></div> }
function Network({ focus = 'dukuh' }: { focus?: string }) { return <svg className="network" viewBox="0 0 360 220" role="img" aria-label="Diagram jaringan LRT Jabodebek dan MRT Jakarta">
  <path className="line lrt" d="M24 168 C82 170 101 126 145 126 S205 93 220 68" />
  <path className="line mrt" d="M220 68 C242 86 268 114 326 53" />
  <path className="line tj" d="M220 68 C255 47 301 43 335 26" />
  {[[24,168,'Bekasi'],[145,126,'Cawang'],[220,68,'Dukuh Atas'],[326,53,'Blok M']].map(([x,y,label]) => <g key={String(label)}><circle className={String(label).toLowerCase().includes(focus) ? 'node active' : 'node'} cx={Number(x)} cy={Number(y)} r="10"/><text x={Number(x)} y={Number(y)+24}>{label}</text></g>)}
</svg> }
function Topbar({ profile, back, title }: { profile: Profile; back?: () => void; title?: string }) { return <header className="topbar">
  {back ? <button className="icon-btn" onClick={back} aria-label="Kembali">←</button> : <Mascot small />}
  <div className="title-area">{title ? <><span className="eyebrow">Dukuh Atas Explorer</span><strong>{title}</strong></> : <><strong>Halo, Penjelajah!</strong><span>Yuk pahami jaringan kota.</span></>}</div>
  <div className="top-stats"><span><b>{icons.fire}</b>{profile.streak}<small>streak</small></span><span><b>{icons.star}</b>{profile.xp}<small>XP</small></span></div>
</header> }
function playFeedback(ok: boolean, enabled: boolean) {
  if (!enabled) return
  const AudioContext = window.AudioContext || (window as Window & { webkitAudioContext?: typeof window.AudioContext }).webkitAudioContext
  if (!AudioContext) return
  const context = new AudioContext(); const oscillator = context.createOscillator(); const gain = context.createGain()
  oscillator.frequency.value = ok ? 660 : 190; gain.gain.value = 0.045; oscillator.connect(gain).connect(context.destination); oscillator.start(); oscillator.stop(context.currentTime + 0.11)
}
function playChainCue(cue: 'move' | 'combo' | 'soft' | 'break' | 'hub', enabled: boolean) {
  if (!enabled) return
  const AudioContext = window.AudioContext || (window as Window & { webkitAudioContext?: typeof window.AudioContext }).webkitAudioContext
  if (!AudioContext) return
  const tones = { move: [470, .06], combo: [760, .09], soft: [260, .1], break: [150, .14], hub: [880, .16] } as const
  const [frequency, duration] = tones[cue]; const context = new AudioContext(); const oscillator = context.createOscillator(); const gain = context.createGain()
  oscillator.frequency.value = frequency; oscillator.type = cue === 'break' ? 'sawtooth' : 'sine'; gain.gain.value = .045; oscillator.connect(gain).connect(context.destination); oscillator.start(); oscillator.stop(context.currentTime + duration)
}

function App() {
  const [profile, setProfile] = useState<Profile>(() => readProfile())
  const [screen, setScreen] = useState<Screen>(profile.onboarded ? 'learn' : 'welcome')
  const [gameIndex, setGameIndex] = useState(0)
  const [chainScenarioId, setChainScenarioId] = useState('dukuh-blokm')
  const [atlasPractice, setAtlasPractice] = useState<RoutePracticeScenario | null>(null)
  const [exploreStationId, setExploreStationId] = useState<string | undefined>()
  const [result, setResult] = useState<{ challenge: Challenge; ok: boolean; message: string; rewardEarned: number; chainSummary?: ChainRunSummary; pipeSummary?: PipeRushRunSummary; isNewPipeBest?: boolean } | null>(null)
  const save = (p: Profile) => { setProfile(p); writeProfile(p) }
  useEffect(() => { if ('serviceWorker' in navigator) navigator.serviceWorker.register('/sw.js').catch(() => undefined) }, [])
  const completed = profile.completed.length
  const start = (onboardingPath: NonNullable<Profile['onboardingPath']> = 'new') => { save({ ...profile, onboarded: true, onboardingPath, demoMode: false }); setScreen('learn') }
  const startDemo = () => { save(demoProfile); setGameIndex(0); setScreen('lesson') }
  const finish = (challenge: Challenge, ok: boolean, expired = false, summary?: ChainRunSummary | PipeRushRunSummary) => {
    const chainSummary = summary && 'maxCombo' in summary ? summary : undefined
    const pipeSummary = summary && 'stars' in summary ? summary : undefined
    const chainClaim = chainSummary && ok ? claimChainScenarioReward(profile, chainSummary.scenarioId, chainSummary.reward) : { profile, rewardEarned: 0, firstCompletion: false }
    const pipeClaim = pipeSummary && ok ? claimPipeRushReward(profile, challenge.id, pipeSummary.scenarioId, pipeSummary.durationMs, pipeSummary.baseReward + pipeSummary.perfectBonus) : { profile, rewardEarned: 0, firstCompletion: false, isNewBest: false }
    const challengeAlready = profile.completed.includes(challenge.id)
    const rewardEarned = chainSummary ? chainClaim.rewardEarned : pipeSummary ? pipeClaim.rewardEarned : ok && !challengeAlready ? challenge.reward : 0
    const rewardProfile = chainSummary ? chainClaim.profile : pipeSummary ? pipeClaim.profile : profile
    const updated: Profile = {
      ...rewardProfile,
      xp: chainSummary || pipeSummary ? rewardProfile.xp : profile.xp + rewardEarned,
      completed: ok && !challengeAlready ? [...profile.completed, challenge.id] : profile.completed,
      completedChainScenarioIds: rewardProfile.completedChainScenarioIds,
      attempts: [...profile.attempts, {
        challengeId: challenge.id, scenarioId: chainSummary?.scenarioId ?? pipeSummary?.scenarioId, outcome: ok ? 'correct' : 'wrong', durationMs: chainSummary?.durationMs ?? pipeSummary?.durationMs ?? 0,
        mistakes: chainSummary?.softMistakes ?? (pipeSummary ? Math.max(0, pipeSummary.stepsUsed - pipeSummary.minSteps) : ok ? 0 : 1), maxCombo: chainSummary?.maxCombo,
        softMistakes: chainSummary?.softMistakes, hardBreaks: chainSummary?.hardBreaks, timeouts: chainSummary?.timeouts, efficiency: chainSummary?.efficiency,
      }],
    }
    save(updated); playFeedback(ok, profile.sound); setResult({ challenge, ok, chainSummary, pipeSummary, isNewPipeBest: pipeClaim.isNewBest, rewardEarned, message: ok ? 'Rute kamu tersambung!' : expired ? 'Waktu habis—coba lagi dan ikuti KRL Bogor hingga Kota.' : 'Belum tepat—coba lihat koneksinya lagi.' }); setScreen('result')
  }
  const game = challenges[gameIndex]
  return <main className={`app-shell ${screen === 'welcome' ? 'onboarding-shell' : ''} ${screen === 'atlas' || screen === 'atlas-practice' ? 'atlas-shell' : ''}`}>
    {screen === 'welcome' && <Welcome profile={profile} onStart={start} onDemo={startDemo} />}
    {screen === 'learn' && <LearningPath profile={profile} onOpenExplore={() => setScreen('explore')} onUpdateLessonProgress={(id, lessonProgress) => save({ ...profile, lessonProgress: { ...(profile.lessonProgress ?? {}), [id]: lessonProgress } })} onCompleteLesson={(id, lessonProgress) => !profile.completedLessons?.includes(id) && save({ ...profile, completedLessons: [...(profile.completedLessons ?? []), id], lessonProgress: { ...(profile.lessonProgress ?? {}), [id]: lessonProgress }, xp: profile.xp + 20 })} />}
    {screen === 'explore' && <Explore profile={profile} onBackToLearn={() => setScreen('learn')} initialStopId={exploreStationId} />}
    {screen === 'atlas' && <Atlas onOpenPractice={(scenario) => { setAtlasPractice(scenario); setScreen('atlas-practice') }} onLearnStation={(stationId) => { setExploreStationId(stationId); setScreen('explore') }} />}
    {screen === 'atlas-practice' && atlasPractice && <AtlasRoutePractice scenario={atlasPractice} onBack={() => setScreen('atlas')} />}
    {screen === 'lesson' && <Lesson profile={profile} onBack={() => setScreen('learn')} onPlay={() => { setGameIndex(1); setChainScenarioId('dukuh-blokm'); setScreen('game') }} />}
    {screen === 'main' && <MainGameHub profile={profile} onPlayPipe={() => { setGameIndex(0); setScreen('game') }} onPlayChain={() => { setGameIndex(1); setChainScenarioId('dukuh-blokm'); setScreen('game') }} />}
    {screen === 'game' && <Game challenge={game} profile={profile} initialChainScenarioId={chainScenarioId} onBack={() => setScreen('learn')} onFinish={finish} />}
    {screen === 'result' && result && <Result profile={profile} result={result} onNext={() => { if (result.chainSummary) { setScreen('game'); return } if (gameIndex < challenges.length - 1) { setGameIndex(gameIndex + 1); setScreen('game') } else setScreen('progress') }} onRetry={() => setScreen('game')} />}
    {screen === 'progress' && <Progress profile={profile} onBack={() => setScreen('learn')} onToggleSound={() => save({ ...profile, sound: !profile.sound })} onInspect={() => setScreen('inspector')} onReset={() => { resetProfile(); save(defaultProfile); setGameIndex(0); setScreen('welcome') }} />}
    {screen === 'inspector' && <Inspector profile={profile} onBack={() => setScreen('progress')} />}
    {screen !== 'welcome' && <Nav screen={screen} setScreen={setScreen} onOpenMain={() => setScreen('main')} />}
  </main>
}

type OnboardingPath = NonNullable<Profile['onboardingPath']>
function OnboardingBrand({ compact = false }: { compact?: boolean }) { return <div className={`onboarding-brand ${compact ? 'compact' : ''}`} aria-label="Commutopia — belajar transit, jelajahi kota"><svg viewBox="0 0 300 46" aria-hidden="true"><defs><linearGradient id="onboarding-route" x1="0" x2="1"><stop stopColor="#ec2670"/><stop offset=".46" stopColor="#176dd6"/><stop offset="1" stopColor="#3aab55"/></linearGradient></defs><path d="M14 20 H95 C116 20 119 39 140 39 S164 20 185 20 H285" fill="none" stroke="url(#onboarding-route)" strokeWidth="8" strokeLinecap="round"/><circle cx="14" cy="20" r="11" fill="#fff" stroke="#ec2670" strokeWidth="6"/><circle cx="150" cy="39" r="11" fill="#fff" stroke="#111c3c" strokeWidth="6"/><circle cx="286" cy="20" r="11" fill="#fff" stroke="#3aab55" strokeWidth="6"/></svg><strong>commut<span>o</span>pia</strong><small>LEARN TRANSIT · GO ANYWHERE</small></div> }
function OnboardingScene() { return <div className="onboarding-scene" aria-label="Commu berdiri di depan jaringan transit Jakarta"><div className="onboarding-spark spark-a">✦</div><div className="onboarding-spark spark-b">✦</div><div className="scene-orbit orbit-a"/><div className="scene-orbit orbit-b"/><Network focus="dukuh"/><div className="scene-station-pin">●<span>Dukuh Atas</span></div><div className="onboarding-mascot"><Mascot/><span>Halo! Yuk<br/>jelajahi kota.</span></div><div className="scene-train krl">KRL</div><div className="scene-train mrt">MRT</div><div className="scene-train lrt">LRT</div><div className="scene-train tj">TJ</div></div> }
function OnboardingDots({ step }: { step: 1 | 2 }) { return <div className="onboarding-dots" aria-label={`Langkah ${step} dari 2`}><i className={step === 1 ? 'active' : ''}/><i className={step === 2 ? 'active' : ''}/></div> }
function Welcome({ profile, onStart, onDemo }: { profile: Profile; onStart: (path: OnboardingPath) => void; onDemo: () => void }) { const [step, setStep] = useState<1 | 2>(1); const [path, setPath] = useState<OnboardingPath>('new'); const options: Array<{ id: OnboardingPath; icon: string; title: string; copy: string; tone: string }> = [{ id: 'new', icon: '⌖', title: 'Aku baru di Jakarta', copy: 'Mulai dari dasar—pelan tapi pasti.', tone: 'lime' }, { id: 'casual', icon: '▣', title: 'Aku kadang naik transit', copy: 'Kenali hub dan transfer biar makin pede.', tone: 'blue' }, { id: 'challenge', icon: '✦', title: 'Aku mau tes skill', copy: 'Langsung pemanasan dengan tantangan rute.', tone: 'purple' }]; if (step === 2) return <section className="welcome onboarding onboarding-choice"><div className="onboarding-choice-top"><button className="onboarding-back" onClick={() => setStep(1)} aria-label="Kembali ke pengenalan">←</button><OnboardingBrand compact/><span className="onboarding-step">2/2</span></div><header><span className="eyebrow">BIAR MAKIN PAS</span><h1>Mulai dari<br/><em>versi kamu.</em></h1><p>Pilih pengalamanmu. Kami pakai ini untuk menata langkah pertama.</p></header><div className="onboarding-options">{options.map((option) => <button key={option.id} className={`onboarding-option ${option.tone} ${path === option.id ? 'selected' : ''}`} onClick={() => setPath(option.id)} aria-pressed={path === option.id}><i>{option.icon}</i><span><b>{option.title}</b><small>{option.copy}</small></span><em>{path === option.id ? '✓' : '→'}</em></button>)}</div><article className="onboarding-note"><Mascot small/><p><b>Tenang, ya.</b><br/>Pilihan ini bisa kamu ubah kapan saja.</p></article><div className="onboarding-bottom"><OnboardingDots step={step}/><button className="primary cta onboarding-cta" onClick={() => onStart(path)}>Buat jalur belajarku <b>{icons.arrow}</b></button></div></section>; return <section className="welcome onboarding"><div className="onboarding-topline"><span className="onboarding-kicker">JAKARTA TRANSIT CLUB</span><div className="streak-pill">{icons.fire} {profile.streak} HARI STREAK</div></div><OnboardingBrand/><h1>Jago transit<br/><em>kayak warga lokal.</em></h1><p className="lead">Belajar rute, transfer, dan arah perjalanan lewat tantangan singkat yang seru.</p><OnboardingScene/><div className="onboarding-mode-grid"><span className="krl">▣<b>KRL</b><small>Commuter</small></span><span className="mrt">▣<b>MRT</b><small>Jakarta</small></span><span className="lrt">▣<b>LRT</b><small>Jakarta</small></span><span className="tj">▣<b>TransJakarta</b><small>Busway</small></span></div><div className="onboarding-bottom"><OnboardingDots step={step}/><button className="primary cta onboarding-cta" onClick={() => setStep(2)}>Mulai Belajar <b>{icons.arrow}</b></button><button className="demo-entry" onClick={onDemo}>▶ Coba demo 3 menit dulu</button></div></section> }
function Learn({ profile, completed, onLesson, onGame }: { profile: Profile; completed: number; onLesson: () => void; onGame: () => void }) { return <><Topbar profile={profile}/><section className="home-content">{profile.demoMode && <div className="demo-banner">● DEMO MODE <span>Alur presentasi siap dimainkan</span></div>}<article className="hero-card"><div><span className="eyebrow">MISI HARI INI</span><h1>Temukan<br/>kekuatan <em>Dukuh Atas.</em></h1><p>Hub yang menghubungkan LRT, MRT, dan TransJakarta.</p><button className="primary" onClick={onLesson}>Mulai pelajaran {icons.arrow}</button></div><Network focus="dukuh"/></article><section className="section-title"><div><span className="eyebrow">JALUR BELAJARMU</span><h2>Dukuh Atas Explorer</h2></div><span className="progress-chip">{completed}/4 selesai</span></section><div className="lesson-path"><button className="lesson-node done" onClick={onLesson}><b>1</b><span>Kenali<br/>Hub</span></button><i/><button className="lesson-node active" onClick={onGame}><b>2</b><span>Rute dari<br/>Bekasi</span></button><i/><button className="lesson-node"><b>3</b><span>Transfer<br/>MRT</span></button><i/><button className="lesson-node"><b>4</b><span>Mastery<br/>Run</span></button></div><article className="practice-card"><div className="icon-disc">⌁</div><div><span className="eyebrow">SIAP BERMAIN?</span><h2>4 tantangan cepat</h2><p>Bangun intuisi transitmu dalam beberapa menit.</p></div><button className="secondary" onClick={onGame}>Main {icons.arrow}</button></article></section></> }
function Lesson({ profile, onBack, onPlay }: { profile: Profile; onBack: () => void; onPlay: () => void }) { return <><Topbar profile={profile} title="Pelajaran 1 dari 4" back={onBack}/><section className="lesson"><span className="eyebrow">APA ITU HUB?</span><h1>Dukuh Atas,<br/><em>pintu ke mana-mana.</em></h1><p className="lead">Bukan cuma stasiun. Dukuh Atas adalah titik sambung yang membantumu berpindah moda dengan percaya diri.</p><article className="map-card"><Network focus="dukuh"/><div className="map-note"><b>● Dukuh Atas</b><span>LRT • MRT • TransJakarta</span></div></article><div className="why-grid"><article><b>1</b><h3>Banyak jalur</h3><p>Beberapa moda bertemu di satu kawasan.</p></article><article><b>2</b><h3>Transfer cerdas</h3><p>Ganti moda tanpa mengulang perjalanan.</p></article><article><b>3</b><h3>Lebih banyak pilihan</h3><p>Satu hub membuka banyak tujuan.</p></article></div><article className="mentor-mini"><Mascot small/><p><strong>Tips Commu</strong><br/>Saat bingung, arahkan rute ke hub besar dahulu.</p></article><button className="primary cta" onClick={onPlay}>Coba Rute Pertama {icons.arrow}</button></section></> }
function MainGameHub({ profile, onPlayPipe, onPlayChain }: { profile: Profile; onPlayPipe: () => void; onPlayChain: () => void }) { const games = [{ icon: '⌁', tone: 'pipe', title: 'Pipe Rush', copy: 'Tarik jalur yang benar dan sambungkan stasiun.', action: onPlayPipe, label: 'Main Pipe Rush' }, { icon: '⛓', tone: 'chain', title: 'Chain Reaction', copy: 'Susun pilihan rute dan transfer secara berurutan.', action: onPlayChain, label: 'Main Chain Reaction' }, { icon: '⚡', tone: 'race', title: 'Path Race', copy: 'Bandingkan dua rute dan pilih yang paling efisien.', locked: true }, { icon: '◉', tone: 'flood', title: 'Color Flood', copy: 'Buka jaringan dengan memilih warna jalur.', locked: true }]; return <><Topbar profile={profile} title="Pilih Game"/><section className="game-hub"><header><span className="eyebrow">TRANSIT ARCADE</span><h1>Mainkan cara<br/><em>belajarmu.</em></h1><p>Pilih tantangan yang ingin kamu kuasai hari ini.</p></header><div className="game-hub-grid">{games.map((game) => <article key={game.title} className={`game-hub-card ${game.tone} ${game.locked ? 'locked' : ''}`}><i>{game.icon}</i><div><span>{game.locked ? 'SEGERA HADIR' : 'SIAP DIMAINKAN'}</span><h2>{game.title}</h2><p>{game.copy}</p></div>{game.locked ? <button disabled>🔒 Terkunci</button> : <button onClick={game.action}>{game.label} <b>→</b></button>}</article>)}</div></section></> }

/* Legacy mini-graph Chain Reaction retained for reference.
const chainServiceLabel = (id: string) => id === 'MRT_NS' ? 'MRT Jakarta' : id === 'LRT_BEKASI' ? 'LRT Jabodebek' : id === 'TJ_1' ? 'TransJakarta 1' : id === 'KRL_CIKARANG_LOOP' ? 'KRL Cikarang Loop' : id === 'KRL_BOGOR' ? 'KRL Bogor Line' : 'Airport Rail Link'
const chainServiceTone = (id: string) => id === 'MRT_NS' ? 'mrt' : id === 'LRT_BEKASI' ? 'lrt' : id.includes('KRL') ? 'krl' : id === 'TJ_1' ? 'tj' : 'airport'
function ChainMap({ path, currentId, targetId, moving, failedTo }: { path: string[]; currentId: string; targetId: string; moving?: boolean; failedTo?: string }) { const coords: Record<string, [number, number]> = { bekasi:[30,190], cawang:[96,142], 'dukuh-atas':[176,80], 'blok-m':[315,130], jatinegara:[40,176], manggarai:[150,108], kota:[292,70], bandara:[292,186] }; const point = (id: string) => coords[nodeById(id)?.placeId ?? ''] ?? [178,160]; const pts = path.map((id) => point(id).join(',')).join(' '); const cur=point(currentId), target=point(targetId), fail=failedTo ? point(failedTo) : null; const isKrl = ['jatinegara','manggarai','kota','bandara'].some((id)=>id===nodeById(currentId)?.placeId || id===nodeById(targetId)?.placeId); return <svg className={`chain-map ${isKrl ? 'krl-scope' : ''}`} viewBox="0 0 356 225" role="img" aria-label="Peta Chain Reaction"><path className="chain-map-line lrt-line" d="M30 190 L96 142 L176 80"/><path className="chain-map-line mrt-line" d="M176 80 L315 130"/><path className="chain-map-line krl-line" d="M40 176 L150 108 L292 70"/><path className="chain-map-line airport-line" d="M150 108 L292 186"/>{path.length > 1 && <polyline className="chain-map-progress" points={pts}/>} {fail && <line className="chain-map-fail" x1={cur[0]} y1={cur[1]} x2={fail[0]} y2={fail[1]}/>} {Object.entries(coords).filter(([id]) => isKrl ? ['jatinegara','manggarai','kota','bandara'].includes(id) : ['bekasi','cawang','dukuh-atas','blok-m'].includes(id)).map(([id,[x,y]]) => <g key={id}><circle className={id===nodeById(currentId)?.placeId?'chain-map-node current':id===nodeById(targetId)?.placeId?'chain-map-node target':'chain-map-node'} cx={x} cy={y} r="9"/><text x={x} y={y+23}>{places.find((p)=>p.id===id)?.name.replace(' (Jakarta Kota)','') ?? id}</text></g>)}{moving && <g className="train-token"><rect x={cur[0]-10} y={cur[1]-7} width="20" height="14" rx="3"/><circle cx={cur[0]-5} cy={cur[1]+8} r="3"/><circle cx={cur[0]+5} cy={cur[1]+8} r="3"/></g>}<circle className="chain-pulse" cx={cur[0]} cy={cur[1]} r="16"/></svg> }
function ChainReactionGame({ challenge, profile, onBack, onFinish }: { challenge: Challenge; profile: Profile; onBack: () => void; onFinish: (c: Challenge, ok: boolean, expired?: boolean, chainSummary?: ChainRunSummary) => void }) {
  const [scenario,setScenario]=useState<ChainScenario>(chainScenarios[0]); const [phase,setPhase]=useState<'start'|'choosing_line'|'choosing_stop'|'growing'|'hub_bonus'|'soft_mistake'|'hard_break'|'complete'|'mentor'>('start'); const [current,setCurrent]=useState(scenario.startNodeId); const [path,setPath]=useState<string[]>([scenario.startNodeId]); const [selectedService,setSelectedService]=useState<string|null>(null); const [relaxed,setRelaxed]=useState(false); const [seconds,setSeconds]=useState(5); const [combo,setCombo]=useState(0); const [maxCombo,setMaxCombo]=useState(0); const [score,setScore]=useState(0); const [softMistakes,setSoftMistakes]=useState(0); const [hardBreaks,setHardBreaks]=useState(0); const [startedAt,setStartedAt]=useState(0); const [notice,setNotice]=useState(''); const [lastSoft,setLastSoft]=useState(false); const [failedTo,setFailedTo]=useState<string>();
  const allEdges=chainEdgesFor(current); const lineIds=[...new Set(allEdges.map((e)=>e.serviceId??nodeById(e.to)?.serviceId).filter(Boolean) as string[])]; const stopEdges=selectedService?allEdges.filter((e)=>(e.serviceId??nodeById(e.to)?.serviceId)===selectedService):[]; const step=Math.min(path.length,scenario.optimalNodeIds.length);
  const begin=(next=scenario)=>{setCurrent(next.startNodeId);setPath([next.startNodeId]);setSelectedService(null);setSeconds(5);setCombo(0);setMaxCombo(0);setScore(0);setSoftMistakes(0);setHardBreaks(0);setFailedTo(undefined);setNotice('');setPhase('choosing_line');setStartedAt(Date.now())};
  useEffect(()=>{if(!startedAt||relaxed||(phase!=='choosing_line'&&phase!=='choosing_stop'))return;if(seconds<=0){setCombo(0);setSoftMistakes(v=>v+1);setLastSoft(false);setNotice('Waktu habis. Pilih langkah ini lagi untuk melanjutkan.');setPhase('soft_mistake');return}const t=window.setTimeout(()=>setSeconds(v=>v-1),1000);return()=>window.clearTimeout(t)},[seconds,phase,relaxed,startedAt]);
  useEffect(()=>{if(phase!=='growing')return;const t=window.setTimeout(()=>{const place=nodeById(current)?.placeId;if(place&&scenario.hubFacts[place]&&path.length>1){playChainCue('hub',profile.sound);setNotice(scenario.hubFacts[place]);setScore(v=>v+150);setPhase('hub_bonus')}else if(lastSoft){playChainCue('soft',profile.sound);setNotice('Bukan rute paling efisien, tetapi kamu masih bisa mencapai tujuan.');setPhase('soft_mistake')}else{setSelectedService(null);setSeconds(5);setPhase('choosing_line')}},520);return()=>window.clearTimeout(t)},[phase,current,path.length,scenario,lastSoft,profile.sound]);
  useEffect(()=>{if(phase!=='hub_bonus'&&phase!=='soft_mistake')return;const t=window.setTimeout(()=>{setSelectedService(null);setSeconds(phase==='soft_mistake'&&lastSoft?4:5);setLastSoft(false);setPhase('choosing_line')},phase==='hub_bonus'?1150:900);return()=>window.clearTimeout(t)},[phase,lastSoft]);
  const chooseStop=(to:string)=>{if(to==='bandara-airport'&&scenario.id==='jatinegara-kota'){playChainCue('break',profile.sound);setFailedTo(to);setCombo(0);setHardBreaks(v=>v+1);setNotice('Airport Rail Link benar-benar berangkat dari Manggarai, tetapi tidak membawa kamu ke Kota dalam misi ini.');setPhase('hard_break');return}const expected=scenario.optimalNodeIds[path.length];const optimal=to===expected;const nextCombo=optimal?combo+1:0;playChainCue(optimal&&nextCombo>1?'combo':'move',profile.sound);setCombo(nextCombo);setMaxCombo(v=>Math.max(v,nextCombo));setScore(v=>v+(optimal?60*Math.max(1,nextCombo):20));if(!optimal)setSoftMistakes(v=>v+1);setLastSoft(!optimal);setCurrent(to);setPath(v=>[...v,to]);if(nodeById(to)?.placeId===nodeById(scenario.endNodeId)?.placeId){setPhase('complete');return}setPhase('growing')};
  const checkpoint=()=>{const last=[...path].reverse().find(id=>scenario.checkpointNodeIds.includes(id))??scenario.startNodeId;setCurrent(last);setPath(v=>v.slice(0,v.lastIndexOf(last)+1));setFailedTo(undefined);setSelectedService(null);setSeconds(5);setPhase('choosing_line')}; const summary=():ChainRunSummary=>({scenarioId:scenario.id,title:scenario.title,difficulty:scenario.difficulty,length:scenario.length,reward:scenario.reward,startName:scenario.startName,endName:scenario.endName,serviceNames:scenario.serviceNames,insight:scenario.insight,totalSteps:scenario.stationIds.length-1,score,maxCombo,hops:path.length-1,softMistakes:softMistakes+hardBreaks,durationMs:Date.now()-startedAt,efficient:softMistakes===0&&hardBreaks===0}); const currentLabel=nodeById(current)?.label??current,targetLabel=nodeById(scenario.endNodeId)?.label??scenario.endNodeId;
  if(phase==='start')return <><Topbar profile={profile} title="Chain Reaction" back={onBack}/><section className="chain-game chain-start reference-shell"><div className="chain-hero"><Mascot/><span>Siap membangun<br/>rute terbaikmu?</span></div><span className="eyebrow">PILIH MISI</span><div className="scenario-picker">{chainScenarios.map(item=><button key={item.id} className={scenario.id===item.id?'selected':''} onClick={()=>{setScenario(item);setCurrent(item.startNodeId);setPath([item.startNodeId])}}><b>{item.title}</b><small>{item.difficulty} · {item.mapScope}</small></button>)}</div><article className="chain-mission"><span>MISIMU</span><h1>{scenario.title.replace(' → ',' ')} <em>→</em></h1><p>Bangun rute transit paling efisien menuju tujuan.</p><div><b>◷ 5 detik/step</b><b>⌘ {scenario.expectedHops}</b><b>▥ {scenario.difficulty}</b></div></article><label className="relaxed-toggle"><input type="checkbox" checked={relaxed} onChange={e=>setRelaxed(e.target.checked)}/> Mode santai — tanpa timer</label><button className="primary cta" onClick={()=>begin()}>Start Challenge <b>→</b></button></section></>
  if(phase==='hub_bonus')return <><Topbar profile={profile} title="Chain Reaction" back={onBack}/><section className="hub-celebration"><div className="hub-stars">✦ ✧ ✦ ✧ ✦</div><span>HUB REACHED!</span><h1>Manggarai</h1><div className="hub-station">⌂</div><b>✦ +150 XP</b><article><strong>Tahukah kamu?</strong><p>{notice}</p><Mascot small/></article><div className="chain-footer">Combo ×{Math.max(1,combo)} <i/> ● ● ●</div></section></>
  if(phase==='hard_break')return <><Topbar profile={profile} title="Chain Reaction" back={onBack}/><section className="chain-game reference-shell phase-hard_break"><ChainHud step={step} seconds={seconds} relaxed={relaxed} combo={combo} score={score}/><RouteHeader from={currentLabel} to={targetLabel}/><p className="danger-copy">Dead end! Jalur ini tidak membawa kamu ke tujuan.</p><ChainMap path={path} currentId={current} targetId={scenario.endNodeId} failedTo={failedTo}/><article className="hard-card"><b>↻ Coba jalur lain!</b><span>Mulai lagi dari hub terakhir: {nodeById(scenario.checkpointNodeIds.at(-1)??scenario.startNodeId)?.label}</span></article><button className="primary cta" onClick={checkpoint}>Kembali ke Checkpoint <b>→</b></button></section></>
  if(phase==='complete')return <><Topbar profile={profile} title="Chain Reaction" back={onBack}/><section className="chain-game chain-complete reference-shell"><span className="eyebrow">RUTE TERSAMBUNG</span><h1>Great Route! ✨</h1><RouteHeader from={nodeById(scenario.startNodeId)?.label??''} to={targetLabel}/><div className="result-time"><b>{Math.max(1,Math.round((Date.now()-startedAt)/1000))} dtk</b><span>Total waktu</span></div><div className="chain-score-grid"><span><b>{path.length-1}</b> hop</span><span><b>×{maxCombo||1}</b> combo</span><span><b>{score}</b> skor</span></div><ChainMap path={path} currentId={current} targetId={scenario.endNodeId}/><div className="result-actions"><button className="secondary" onClick={()=>begin()}>↻ Replay</button><button className="primary" onClick={()=>setPhase('mentor')}>Lihat Insight →</button></div></section></>
  if(phase==='mentor')return <><Topbar profile={profile} title="Insight Commu" back={onBack}/><section className="chain-game mentor-screen"><div className="mentor-hero"><Mascot/><span>Nice work! Ini yang<br/>kamu pelajari hari ini.</span></div><article><span className="eyebrow">AI MENTOR INSIGHT</span><h2>{scenario.id==='jatinegara-kota'?'Manggarai mengubah arah perjalananmu.':'Transfer tepat membuka koridor baru.'}</h2><p>{scenario.id==='jatinegara-kota'?'Dari Jatinegara, Manggarai adalah titik untuk berganti dari Cikarang Loop ke Bogor Line menuju Kota.':'Dukuh Atas membuat perpindahan LRT ke MRT menjadi strategi paling langsung ke Blok M.'}</p></article><div className="improved"><span>⌘<b>Route planning</b><small>Bagus!</small></span><span>⌂<b>Hub knowledge</b><small>Naik level</small></span><span>◷<b>Efficiency</b><small>{softMistakes?'Coba ulang':'Hebat!'}</small></span></div><button className="primary cta" onClick={()=>onFinish(challenge,true,false,summary())}>Kembali ke Map <b>⌂</b></button></section></>
  const transient=phase==='growing'||phase==='soft_mistake'; return <><Topbar profile={profile} title="Chain Reaction" back={onBack}/><section className={`chain-game reference-shell phase-${phase}`}><ChainHud step={step} seconds={seconds} relaxed={relaxed} combo={combo} score={score}/><RouteHeader from={currentLabel} to={targetLabel}/><p className={phase==='soft_mistake'?'soft-copy':'chain-instruction'}>{phase==='growing'?'Jalur sedang tersambung…':phase==='soft_mistake'?'⚠ Bukan rute paling efisien. Combo direset.':phase==='choosing_line'?'Pilih jalur berikutnya':'Pilih stop berikutnya'}</p><ChainMap path={path} currentId={current} targetId={scenario.endNodeId} moving={phase==='growing'}/>{transient?<article className="chain-feedback" role="status"><b>{phase==='growing'?'Kereta bergerak':'Kamu masih dapat mencapai tujuan'}</b><span>{notice||'Membaca jalur…'}</span></article>:<article className="chain-sheet"><span className="eyebrow">{phase==='choosing_line'?`JALUR DARI ${currentLabel.toUpperCase()}`:`PILIH STOP VIA ${chainServiceLabel(selectedService!)}`}</span><div className="chain-options">{phase==='choosing_line'?lineIds.map(id=><button key={id} className={`chain-option ${chainServiceTone(id)}`} onClick={()=>{setSelectedService(id);setSeconds(5);setPhase('choosing_stop')}}><i>▣</i><span><b>{chainServiceLabel(id)}</b><small>→ {allEdges.filter(e=>(e.serviceId??nodeById(e.to)?.serviceId)===id).map(e=>nodeById(e.to)?.label).join(', ')}</small></span></button>):stopEdges.map(edge=><button key={edge.to} className="chain-option stop" onClick={()=>chooseStop(edge.to)}><i>●</i><span><b>{nodeById(edge.to)?.label}</b><small>{chainServiceLabel(selectedService!)}</small></span><em>→</em></button>)}</div>{phase==='choosing_stop'&&<button className="back-line" onClick={()=>{setSelectedService(null);setPhase('choosing_line')}}>← Pilih jalur lain</button>}</article>}</section></> }
function ChainHud({step,seconds,relaxed,combo,score}:{step:number;seconds:number;relaxed:boolean;combo:number;score:number}){return <div className="chain-hud"><span>Ⅱ</span><b>STEP {step} OF 4</b><i>{relaxed?'∞ SANTAI':`◷ 0${seconds}:00`}</i><em>Combo ×{Math.max(1,combo)} · {score} XP</em></div>}
function RouteHeader({from,to}:{from:string;to:string}){return <div className="route-header"><b>{from}<i/></b><span>›››</span><strong>⌖ {to}</strong></div>}
*/

type ChainPhase = 'start' | 'line' | 'stop' | 'moving' | 'soft' | 'break' | 'complete'
function RouteHeader({ from, to }: { from: string; to: string }) { return <div className="route-header"><b>{from}<i/></b><span>›››</span><strong>⌖ {to}</strong></div> }
function ChainProgress({ scenario, path, current }: { scenario: ChainScenario; path: string[]; current: string }) { const index = Math.min(path.length - 1, scenario.stationIds.length - 1); const visible = scenario.stationIds.slice(Math.max(0, index - 2), Math.min(scenario.stationIds.length, index + 4)); return <section className="chain-route-progress"><header><span>ROUTE PROGRESS</span><b>{index}/{scenario.expectedHops} hop</b></header><div>{visible.map((id) => { const station = transitGraph.stationById.get(id)!; const line = transitGraph.lineById.get(station.serviceId); const isCurrent = id === scenario.stationIds[index]; return <span key={id} className={isCurrent ? 'current' : scenario.stationIds.indexOf(id) < index ? 'done' : ''} style={{ '--route': line?.color } as CSSProperties}><i/>{station.name}</span> })}</div><small>Posisi kini: <b>{transitGraph.stationById.get(current)?.name}</b></small></section> }
function ChainReactionGame({ challenge, profile, onBack, onFinish }: { challenge: Challenge; profile: Profile; onBack: () => void; onFinish: (c: Challenge, ok: boolean, expired?: boolean, chainSummary?: ChainRunSummary) => void }) {
  const [scenario, setScenario] = useState(chainScenarios[0]); const [phase, setPhase] = useState<ChainPhase>('start'); const [current, setCurrent] = useState(scenario.startStationId); const [path, setPath] = useState<string[]>([scenario.startStationId]); const [action, setAction] = useState<ChainAction | null>(null); const [relaxed, setRelaxed] = useState(false); const [seconds, setSeconds] = useState(scenario.secondsPerStep); const [score, setScore] = useState(0); const [combo, setCombo] = useState(0); const [maxCombo, setMaxCombo] = useState(0); const [mistakes, setMistakes] = useState(0); const [started, setStarted] = useState(0); const [message, setMessage] = useState('');
  const reset = (next = scenario) => { setCurrent(next.startStationId); setPath([next.startStationId]); setAction(null); setSeconds(next.secondsPerStep); setScore(0); setCombo(0); setMaxCombo(0); setMistakes(0); setMessage(''); setStarted(Date.now()); setPhase('line') }
  const currentStation = transitGraph.stationById.get(current); const actions = actionsForStation(current); const step = Math.min(path.length, scenario.expectedHops)
  useEffect(() => { if (!started || relaxed || (phase !== 'line' && phase !== 'stop')) return; if (seconds <= 0) { setMistakes((value) => value + 1); setCombo(0); setMessage('Waktu habis. Pilih langkah ini lagi.'); setPhase('soft'); return } const timer = window.setTimeout(() => setSeconds((value) => value - 1), 1000); return () => window.clearTimeout(timer) }, [seconds, phase, relaxed, started])
  useEffect(() => { if (phase !== 'moving' && phase !== 'soft') return; const timer = window.setTimeout(() => { setAction(null); setSeconds(scenario.secondsPerStep); setPhase('line') }, phase === 'moving' ? 420 : 900); return () => window.clearTimeout(timer) }, [phase, scenario.secondsPerStep])
  const choose = (edge: ChainAction['edges'][number]) => { const optimal = edge.to === scenario.stationIds[path.length]; if (!optimal && !canReachScenarioGoal(edge.to, scenario, path)) { setMessage('Jalur ini buntu untuk misi ini. Kembali ke checkpoint terakhir.'); setCombo(0); setMistakes((value) => value + 1); setPhase('break'); return } const nextCombo = optimal ? combo + 1 : 0; setCombo(nextCombo); setMaxCombo((value) => Math.max(value, nextCombo)); setScore((value) => value + (optimal ? 60 * Math.max(1, nextCombo) : 20)); if (!optimal) { setMistakes((value) => value + 1); setMessage('Masih bisa lanjut, tapi ini bukan urutan tercepat.'); setPhase('soft') } else setPhase('moving'); setCurrent(edge.to); setPath((value) => [...value, edge.to]); if (edge.to === scenario.endStationId) setPhase('complete') }
  const checkpoint = () => { const last = [...path].reverse().find((id) => scenario.checkpointStationIds.includes(id)) ?? scenario.startStationId; setCurrent(last); setPath((value) => value.slice(0, value.lastIndexOf(last) + 1)); setAction(null); setSeconds(scenario.secondsPerStep); setPhase('line') }
  const finish = () => onFinish(challenge, true, false, { scenarioId: scenario.id, title: scenario.title, difficulty: scenario.difficulty, length: scenario.length, reward: scenario.reward, startName: scenario.startName, endName: scenario.endName, serviceNames: scenario.serviceNames, insight: scenario.insight, totalSteps: scenario.expectedHops, score, maxCombo, hops: path.length - 1, softMistakes: mistakes, durationMs: Date.now() - started, efficient: mistakes === 0 })
  if (phase === 'start') return <><Topbar profile={profile} title="Chain Reaction" back={onBack}/><section className="chain-game chain-start"><div className="chain-hero"><Mascot/><span>6 misi baru,<br/>pilih rute terbaikmu.</span></div>{(['Easy', 'Medium', 'High'] as const).map((tier) => <section className="chain-tier" key={tier}><header><b>{tier}</b><small>{tier === 'Easy' ? 'Mulai pelan' : tier === 'Medium' ? 'Butuh transfer' : 'Rute jauh & fokus'}</small></header><div className="scenario-picker">{chainScenarios.filter((item) => item.difficulty === tier).map((item) => <button key={item.id} className={scenario.id === item.id ? 'selected' : ''} onClick={() => { setScenario(item); setCurrent(item.startStationId); setPath([item.startStationId]); setSeconds(item.secondsPerStep) }}><span><b>{item.title}</b><small>{item.expectedHops} hop · {item.transferCount} transfer · {item.reward} XP</small></span>{item.length !== 'standard' && <em>{item.length === 'marathon' ? 'MARATHON' : 'LONG'}</em>}{profile.completedChainScenarioIds.includes(item.id) && <i>✓</i>}</button>)}</div></section>)}<article className="chain-mission"><span>MISIMU</span><h1>{scenario.title}</h1><p>{scenario.expectedHops} hop · {scenario.transferCount} transfer · {scenario.secondsPerStep} dtk/step</p></article><label className="relaxed-toggle"><input type="checkbox" checked={relaxed} onChange={(event) => setRelaxed(event.target.checked)}/> Mode santai — tanpa timer</label><button className="primary cta" onClick={() => reset()}>Start Challenge <b>→</b></button></section></>
  if (phase === 'complete') return <><Topbar profile={profile} title="Chain Reaction" back={onBack}/><section className="chain-game chain-complete"><span className="eyebrow">RUTE TERSAMBUNG</span><h1>Great Route! ✨</h1><RouteHeader from={scenario.startName} to={scenario.endName}/><ChainProgress scenario={scenario} path={path} current={current}/><div className="chain-score-grid"><span><b>{path.length - 1}</b> hop</span><span><b>×{maxCombo || 1}</b> combo</span><span><b>{score}</b> skor</span></div><article className="chain-feedback"><b>{scenario.insight}</b><span>{scenario.length === 'marathon' ? 'Marathon selesai—kamu berhasil membaca seluruh chain.' : 'Lanjutkan ke misi lain untuk variasi rute.'}</span></article><div className="result-actions"><button className="secondary" onClick={() => reset()}>↻ Replay</button><button className="primary" onClick={finish}>Lihat hasil →</button></div></section></>
  if (phase === 'break') return <><Topbar profile={profile} title="Chain Reaction" back={onBack}/><section className="chain-game"><RouteHeader from={scenario.startName} to={scenario.endName}/><ChainProgress scenario={scenario} path={path} current={current}/><article className="hard-card"><b>↻ Jalur buntu</b><span>{message}</span></article><button className="primary cta" onClick={checkpoint}>Kembali ke Checkpoint <b>→</b></button></section></>
  return <><Topbar profile={profile} title="Chain Reaction" back={onBack}/><section className="chain-game"><ChainHud step={step} total={scenario.expectedHops} seconds={seconds} relaxed={relaxed} combo={combo} score={score}/><RouteHeader from={scenario.startName} to={scenario.endName}/><ChainProgress scenario={scenario} path={path} current={current}/><p className={phase === 'soft' ? 'soft-copy' : 'chain-instruction'}>{phase === 'moving' ? 'Jalur sedang tersambung…' : phase === 'soft' ? message : phase === 'line' ? 'Pilih jalur atau transfer berikutnya' : 'Pilih stop berikutnya'}</p>{phase === 'moving' || phase === 'soft' ? <article className="chain-feedback"><b>{phase === 'moving' ? 'Kereta bergerak' : 'Combo direset'}</b><span>{message || 'Membaca jalur…'}</span></article> : <article className="chain-sheet"><span className="eyebrow">{phase === 'line' ? `DARI ${currentStation?.name.toUpperCase()}` : action?.label.toUpperCase()}</span><div className="chain-options">{phase === 'line' ? actions.map((item) => <button key={item.id} className={`chain-option ${lineTone(item.serviceId)}`} onClick={() => { setAction(item); setSeconds(scenario.secondsPerStep); setPhase('stop') }}><i>{item.kind === 'transfer' ? '↺' : '▣'}</i><span><b>{item.label}</b><small>{item.detail}</small></span></button>) : action?.edges.map((edge) => <button key={edge.id} className="chain-option stop" onClick={() => choose(edge)}><i>{edge.kind === 'transfer' ? '↺' : '●'}</i><span><b>{transitGraph.stationById.get(edge.to)?.name}</b><small>{edge.kind === 'transfer' ? 'Transfer hub' : action.label}</small></span><em>→</em></button>)}</div>{phase === 'stop' && <button className="back-line" onClick={() => setPhase('line')}>← Pilih jalur lain</button>}</article>}</section></>
}
function ChainHud({ step, total, seconds, relaxed, combo, score }: { step: number; total: number; seconds: number; relaxed: boolean; combo: number; score: number }) { return <div className="chain-hud"><span>Ⅱ</span><b>STEP {step} OF {total}</b><i>{relaxed ? '∞ SANTAI' : `◷ 0:${String(seconds).padStart(2, '0')}`}</i><em>Combo ×{Math.max(1, combo)} · {score} score</em></div> }

function Game({ challenge, profile, initialChainScenarioId, onBack, onFinish }: { challenge: Challenge; profile: Profile; initialChainScenarioId?: string; onBack: () => void; onFinish: (c: Challenge, ok: boolean, expired?: boolean, summary?: ChainRunSummary | PipeRushRunSummary) => void }) {
  if (challenge.mechanic === 'chain') return <ReferenceChainReactionGame challenge={challenge} profile={profile} initialScenarioId={initialChainScenarioId} onBack={onBack} onFinish={onFinish}/>
  if (challenge.mechanic === 'pipe') return <PipeRushGame challenge={challenge} profile={profile} onBack={onBack} onFinish={onFinish}/>
  const [picked, setPicked] = useState<string[]>([])
  const [seconds, setSeconds] = useState(90)
  const [feedback, setFeedback] = useState<'idle' | 'correct' | 'wrong'>('idle')
  useEffect(() => { setPicked([]); setSeconds(90); setFeedback('idle') }, [challenge.id])
  useEffect(() => {
    if (seconds <= 0) { onFinish(challenge, false, true); return }
    const timer = window.setInterval(() => setSeconds((current) => current - 1), 1000)
    return () => window.clearInterval(timer)
  }, [challenge, onFinish, seconds])
  const isList = Array.isArray(challenge.answer)
  const submit = () => {
    const ok = isList ? JSON.stringify(picked) === JSON.stringify(challenge.answer) : picked[0] === challenge.answer
    setFeedback(ok ? 'correct' : 'wrong')
    window.setTimeout(() => onFinish(challenge, ok), ok ? 450 : 600)
  }
  const select = (value: string) => {
    if (challenge.mechanic === 'flood') setPicked((prev) => prev.includes(value) ? prev.filter((x) => x !== value) : [...prev, value])
    else setPicked([value])
  }
  const ready = picked.length > 0
  const minutes = String(Math.floor(seconds / 60)).padStart(2, '0'); const remainder = String(seconds % 60).padStart(2, '0')
  return <><Topbar profile={profile} title={`${challenge.kicker} · ${challenges.indexOf(challenge) + 1}/4`} back={onBack}/><section className="game">
    <div className="game-head"><span className="eyebrow">{challenge.kicker}</span><span className={`timer ${seconds <= 15 ? 'urgent' : ''}`}>◷ {minutes}:{remainder}</span></div><div className="challenge-progress"><span>Challenge {challenges.indexOf(challenge) + 1} dari 4</span><span>{challenge.start} → {challenge.end}</span></div><h1>{challenge.title}</h1><p className="game-prompt">{challenge.prompt}</p>
    <article className={`game-canvas ${challenge.mechanic} ${feedback}`}>
      <div className="route-pills"><span className="start">{challenge.start}</span><i>→</i><span className="target">{challenge.end}</span></div>
      {challenge.mechanic === 'race' && <Race/>}
      {challenge.mechanic === 'flood' && <Flood selected={picked}/>} 
    </article>
    {challenge.mechanic === 'race' && <Options choices={challenge.choices!} selected={picked[0]} onSelect={select} cards/>} 
    {challenge.mechanic === 'flood' && <div className="option-panel"><span className="eyebrow">PILIH WARNA JALUR</span><div className="choice-grid">{challenge.choices!.map((x, i) => <Choice key={x} label={x} tone={i === 0 ? 'pink' : i === 1 ? 'blue' : 'red'} active={picked.includes(x)} onClick={() => select(x)}/>)}</div></div>}
    {feedback === 'wrong' && <p className="inline-feedback" role="status">Belum tersambung. Cek pilihanmu sekali lagi.</p>}
    <button className="primary cta" disabled={!ready || feedback !== 'idle'} onClick={submit}>{challenge.mechanic === 'flood' ? 'Buka Jaringan' : 'Cek Rute'} {icons.arrow}</button>
  </section></>
}
function Pipe({ selected, onSelect }: { selected: string[]; onSelect: (x: string) => void }) { return <div className="pipe-visual"><div className="station">Bekasi</div><button className={`pipe-segment ${selected.includes('bekasi-cawang') ? 'on' : ''}`} onClick={() => onSelect('bekasi-cawang')} aria-label="Ruas Bekasi ke Cawang"/><div className="station">Cawang</div><button className={`pipe-segment ${selected.includes('cawang-dukuh') ? 'on' : ''}`} onClick={() => onSelect('cawang-dukuh')} aria-label="Ruas Cawang ke Dukuh Atas"/><div className="station hub">Dukuh Atas</div></div> }
function Race() { return <div className="race-visual"><div className="race-path blue">Dukuh Atas <b>━━━</b> Blok M<br/><small>7 pemberhentian</small></div><div className="race-path red">Dukuh Atas <b>━━━</b> Blok M<br/><small>9 pemberhentian</small></div></div> }
function Flood({ selected }: { selected: string[] }) { return <div className="flood-visual"><div className={`flood-branch pink ${selected.includes('LRT Bekasi') ? 'lit' : ''}`}>Bekasi ━━━ Dukuh Atas</div><div className={`flood-branch blue ${selected.includes('MRT Jakarta') ? 'lit' : ''}`}>Dukuh Atas ━━━ Blok M</div><div className={`flood-branch red ${selected.includes('TransJakarta Koridor 1') ? 'lit' : ''}`}>Dukuh Atas ━━━ Kota</div></div> }
function Choice({ label, tone, active, onClick }: { label: string; tone: string; active: boolean; onClick: () => void }) { return <button className={`choice ${tone} ${active ? 'selected' : ''}`} onClick={onClick}><i/> {label}</button> }
function Options({ choices, selected, onSelect, cards = false }: { choices: string[]; selected?: string; onSelect: (x: string) => void; cards?: boolean }) { return <div className={cards ? 'race-options' : 'options'}>{choices.map((x, index) => <button key={x} className={`${cards ? 'route-choice' : 'answer-choice'} ${selected === x ? 'selected' : ''}`} onClick={() => onSelect(x)}><b>{cards ? (index === 0 ? 'MRT' : 'TJ') : String.fromCharCode(65 + index)}</b><span>{x}</span>{selected === x && <i>✓</i>}</button>)}</div> }
function Result({ profile, result, onNext, onRetry }: { profile: Profile; result: { challenge: Challenge; ok: boolean; message: string; rewardEarned: number; chainSummary?: ChainRunSummary; pipeSummary?: PipeRushRunSummary; isNewPipeBest?: boolean }; onNext: () => void; onRetry: () => void }) { const mentor = mentorCopy(mentorFor(result.challenge)); const chain = result.chainSummary; const pipe = result.pipeSummary; const routeStart = chain?.startName ?? pipe?.startName ?? result.challenge.start; const routeEnd = chain?.endName ?? pipe?.endName ?? result.challenge.end; const routeServices = chain?.serviceNames.join(' + ') ?? pipe?.serviceNames.join(' + ') ?? result.challenge.solution.serviceIds.join(' + ').replace('LRT_BEKASI','LRT Bekasi').replace('MRT_NS','MRT'); const mentorFacts = chain ? [chain.insight] : pipe ? [pipe.insight] : [mentor.body, mentor.tip]; const rewardLabel = result.rewardEarned ? `+${result.rewardEarned} XP` : chain || pipe ? 'Replay · skor tersimpan' : 'Sudah pernah diklaim'; const pipeTime = pipe ? `${Math.max(1, Math.round(pipe.durationMs / 1000))} dtk` : ''; return <><Topbar profile={profile} title="Hasil Tantangan"/><section className="result"><div className={`result-badge ${result.ok ? 'good' : 'bad'}`}>{result.ok ? '✓' : '!'}</div><span className="eyebrow">{result.ok ? 'RUTE TERSAMBUNG' : 'COBA LAGI'}</span><h1>{result.ok ? pipe ? 'Great Job! ✨' : 'Mantap, Penjelajah!' : 'Hampir berhasil!'}</h1><p className="lead">{result.message}</p>{result.ok && <div className="reward count-up">{icons.star} {rewardLabel} <span>•</span> +1 progress</div>}{pipe && <article className="pipe-result-stats"><span><b>{pipe.score}%</b> skor</span><span><b>{'★'.repeat(pipe.stars)}</b> {pipe.stars} bintang</span><span><b>{pipeTime}</b> waktu</span><span><b>{pipe.stepsUsed}/{pipe.minSteps}</b> langkah</span></article>}{pipe && result.isNewPipeBest && result.ok && <p className="pipe-new-best">✦ Rekor waktu baru!</p>}{chain && <article className="chain-result-stats"><span><b>{chain.score}</b> skor</span><span><b>×{chain.maxCombo || 1}</b> combo</span><span><b>{chain.softMistakes}</b> putaran</span></article>}<TransitMentorCard request={{ purpose: 'explain_why', title: `${routeStart} → ${routeEnd}`, outcome: result.ok ? 'completed' : 'retry', facts: mentorFacts, attempts: { total: profile.attempts.length, correct: profile.attempts.filter((attempt) => attempt.outcome === 'correct').length, transferMistakes: chain?.softMistakes ?? 0 }, allowedPractice: ['Ulangi satu PipeMap untuk membaca urutan stop.', 'Coba Chain Reaction untuk melatih pilihan transfer.'] }}/><article className="solution"><span className="eyebrow">RUTE YANG DIVALIDASI GRAPH</span><div><b>{routeStart}</b><i>→</i><strong>{routeServices}</strong><i>→</i><b>{routeEnd}</b></div></article><button className="primary cta" onClick={result.ok ? onNext : onRetry}>{result.ok ? chain ? 'Pilih misi Chain lain' : 'Tantangan Berikutnya' : 'Coba Lagi'} {icons.arrow}</button></section></> }

function ProgressCoach({ profile }: { profile: Profile }) { const correct = profile.attempts.filter((attempt) => attempt.outcome === 'correct').length; const transferMistakes = profile.attempts.reduce((total, attempt) => total + attempt.mistakes, 0); return <TransitMentorCard request={{ purpose: 'coach', title: 'Rekomendasi belajar berikutnya', facts: ['Dukuh Atas adalah transfer terverifikasi antara LRT Jabodebek dan MRT.', 'Manggarai adalah hub KRL untuk Cikarang Loop dan Bogor Line.', 'Graph Engine tetap menjadi satu-satunya validator rute dan jawaban challenge.'], attempts: { total: profile.attempts.length, correct, transferMistakes }, allowedPractice: transferMistakes > 0 ? ['Belajar hub Dukuh Atas dan latihan transfer terverifikasi.', 'Coba Chain Reaction untuk membangun urutan transfer.'] : ['Lanjutkan ke PipeMap KRL dan pelajari Manggarai.', 'Coba Chain Reaction multi-moda untuk meningkatkan kesulitan.'] }} /> }
function Progress({ profile, onBack, onToggleSound, onInspect, onReset }: { profile: Profile; onBack: () => void; onToggleSound: () => void; onInspect: () => void; onReset: () => void }) { const percent = Math.round((profile.completed.length / 4) * 100); const correct = profile.attempts.filter((attempt) => attempt.outcome === 'correct').length; const reflection = profile.attempts.length >= 4; return <><Topbar profile={profile} title="Progres Kamu" back={onBack}/><section className="progress"><article className="confidence"><span className="eyebrow">TRANSIT CONFIDENCE</span><h1>{percent}%</h1><div className="bar"><i style={{ width: `${percent}%` }}/></div><p>{percent < 100 ? 'Selesaikan semua tantangan untuk menguasai Dukuh Atas.' : 'Kamu siap menjelajah hub besar Jakarta!'}</p></article>{reflection && <article className="reflection"><Mascot small/><div><span className="eyebrow">REFLECTION COACH</span><h3>{correct >= 3 ? 'Kamu sudah membaca pola hub.' : 'Kamu sedang membangun intuisi transfer.'}</h3><p>{correct >= 3 ? 'Kekuatanmu: rute LRT dan pilihan transfer. Berikutnya, coba cari hub lain seperti Cawang.' : 'Ulangi rute Dukuh Atas → Blok M untuk membiasakan satu transfer yang efisien.'}</p></div></article>}<ProgressCoach profile={profile}/><section className="section-title"><div><span className="eyebrow">BADGE</span><h2>Pencapaian</h2></div></section><div className="badge-row"><article className={profile.completed.length ? 'earned' : ''}>⌘<b>Dukuh Atas<br/>Explorer</b><small>{profile.completed.length}/4 tantangan</small></article><article className={profile.completed.length === 4 ? 'earned' : ''}>✦<b>Route Builder</b><small>Selesaikan 4 mekanik</small></article></div><article className="stats-card"><div><b>{profile.xp}</b><span>Total XP</span></div><div><b>{profile.streak}</b><span>Hari beruntun</span></div><div><b>{profile.attempts.length}</b><span>Tantangan</span></div></article><div className="settings-row"><button className="secondary" onClick={onToggleSound}>🔊 Suara: {profile.sound ? 'Aktif' : 'Mati'}</button><button className="secondary" onClick={onInspect}>⌘ Inspektur jaringan</button></div><button className="reset" onClick={onReset}>Reset demo profile</button></section></> }
function Inspector({ profile, onBack }: { profile: Profile; onBack: () => void }) { return <><Topbar profile={profile} title="Inspektur jaringan" back={onBack}/><section className="inspector"><article className="data-source"><span className="eyebrow">SUMBER DATA</span><h2>Jaringan demo tervalidasi</h2><p>{dataAudit.source}</p><div className="audit-stats"><span><b>{dataAudit.services}</b> layanan</span><span><b>{dataAudit.hubs}</b> hub</span><span><b>{edges.length}</b> edge demo</span></div></article><article className="map-card"><Network focus="dukuh"/><div className="map-note"><b>● Dukuh Atas</b><span>{places.find((place) => place.id === 'dukuh-atas')?.modes.join(' • ')}</span></div></article><section className="edge-list"><span className="eyebrow">KONEKSI YANG DIPAKAI DI MVP</span>{edges.map((edge) => { const from = nodes.find((node) => node.id === edge.from)?.label; const to = nodes.find((node) => node.id === edge.to)?.label; return <div key={`${edge.from}-${edge.to}`}><b>{from}</b><i>→</i><b>{to}</b><small>{edge.type === 'ride' ? edge.serviceId === 'LRT_BEKASI' ? 'LRT Jabodebek Bekasi' : edge.serviceId === 'MRT_NS' ? 'MRT Jakarta' : 'TransJakarta Koridor 1' : 'Jalan kaki / transfer'}</small></div> })}</section><p className="inspector-note">Inspektur ini memperlihatkan koneksi yang diizinkan oleh game. Data real-time, tarif, dan estimasi perjalanan sengaja tidak digunakan.</p></section></> }
function Nav({ screen, setScreen, onOpenMain }: { screen: Screen; setScreen: (x: Screen) => void; onOpenMain: () => void }) { return <nav><button className={screen === 'learn' ? 'active' : ''} onClick={() => setScreen('learn')}>⌂<span>Belajar</span></button><button className={screen === 'atlas' || screen === 'atlas-practice' ? 'active' : ''} onClick={() => setScreen('atlas')}>⌘<span>Atlas</span></button><button className={screen === 'explore' ? 'active' : ''} onClick={() => setScreen('explore')}>⌕<span>Explore</span></button><button className={screen === 'main' || screen === 'game' ? 'active' : ''} onClick={onOpenMain}>◎<span>Main</span></button><button className={screen === 'progress' ? 'active' : ''} onClick={() => setScreen('progress')}>▥<span>Progres</span></button></nav> }

createRoot(document.getElementById('root')!).render(<StrictMode><App /></StrictMode>)
