import type { Attempt } from './domain'

export interface LessonProgress { quizzes: boolean[]; practice: boolean }
export interface Profile { version: 1 | 2 | 3 | 4 | 5; onboarded: boolean; xp: number; streak: number; completed: string[]; completedChainScenarioIds: string[]; completedPipeRushScenarioIds: string[]; attempts: Attempt[]; sound: boolean; onboardingPath?: 'new' | 'casual' | 'challenge'; demoMode?: boolean; exploredPlaces?: string[]; completedLessons?: string[]; lessonProgress?: Record<string, LessonProgress>; pipeRushBestTimesMs: Record<string, number> }
const KEY = 'commutopia-profile-v1'
export const defaultProfile: Profile = { version: 5, onboarded: false, xp: 0, streak: 3, completed: [], completedChainScenarioIds: [], completedPipeRushScenarioIds: [], attempts: [], sound: false, exploredPlaces: [], completedLessons: [], lessonProgress: {}, pipeRushBestTimesMs: {} }
export const demoProfile: Profile = { version: 5, onboarded: true, xp: 280, streak: 12, completed: ['pipe-tebet-kota', 'chain-blokm'], completedChainScenarioIds: ['dukuh-blokm'], completedPipeRushScenarioIds: ['tebet-kota'], attempts: [{ challengeId: 'pipe-tebet-kota', scenarioId: 'tebet-kota', outcome: 'correct', durationMs: 32000, mistakes: 0 }, { challengeId: 'chain-blokm', scenarioId: 'dukuh-blokm', outcome: 'correct', durationMs: 24000, mistakes: 0 }, { challengeId: 'race-blokm', outcome: 'correct', durationMs: 20000, mistakes: 0 }, { challengeId: 'flood-dukuh', outcome: 'wrong', durationMs: 28000, mistakes: 1 }], sound: false, demoMode: true, exploredPlaces: ['dukuh-atas', 'manggarai'], completedLessons: ['u1-l1', 'u1-l2'], lessonProgress: { 'u1-l1': { quizzes: [true, true], practice: true }, 'u1-l2': { quizzes: [true, true], practice: true } }, pipeRushBestTimesMs: { 'tebet-kota': 32000 } }
export function migrateProfile(stored: Partial<Profile>): Profile { const completedLessons = stored.completedLessons ?? []; const lessonProgress = { ...(stored.lessonProgress ?? {}) }; completedLessons.forEach((id) => { lessonProgress[id] ??= { quizzes: [true, true], practice: true } }); const completedChainScenarioIds = [...new Set([...(stored.completedChainScenarioIds ?? []), ...(stored.completed?.includes('chain-blokm') ? ['dukuh-blokm'] : [])])]; const completedPipeRushScenarioIds = [...new Set([...(stored.completedPipeRushScenarioIds ?? []), ...(stored.completed?.includes('pipe-tebet-kota') ? ['tebet-kota'] : [])])]; const completed = (stored.completed ?? []).filter((id) => id !== 'pipe-dukuh'); return { ...defaultProfile, ...stored, version: 5, completed, completedLessons, completedChainScenarioIds, completedPipeRushScenarioIds, lessonProgress, pipeRushBestTimesMs: { ...(stored.pipeRushBestTimesMs ?? {}) } } }
export function claimChainScenarioReward(profile: Profile, scenarioId: string, reward: number) { if (profile.completedChainScenarioIds.includes(scenarioId)) return { profile, rewardEarned: 0, firstCompletion: false }; return { profile: { ...profile, xp: profile.xp + reward, completedChainScenarioIds: [...profile.completedChainScenarioIds, scenarioId] }, rewardEarned: reward, firstCompletion: true } }
export function claimPipeRushReward(profile: Profile, challengeId: string, scenarioId: string, durationMs: number, reward: number) { const previous = profile.pipeRushBestTimesMs[scenarioId]; const isNewBest = previous === undefined || durationMs < previous; const firstCompletion = !profile.completedPipeRushScenarioIds.includes(scenarioId); const rewardEarned = firstCompletion ? reward : 0; return { profile: { ...profile, xp: profile.xp + rewardEarned, completedPipeRushScenarioIds: firstCompletion ? [...profile.completedPipeRushScenarioIds, scenarioId] : profile.completedPipeRushScenarioIds, pipeRushBestTimesMs: isNewBest ? { ...profile.pipeRushBestTimesMs, [scenarioId]: durationMs } : profile.pipeRushBestTimesMs }, rewardEarned, firstCompletion, isNewBest } }
export function readProfile(): Profile { try { return migrateProfile(JSON.parse(localStorage.getItem(KEY) || '{}') as Partial<Profile>) } catch { return defaultProfile } }
export function writeProfile(profile: Profile) { localStorage.setItem(KEY, JSON.stringify(profile)) }
export function resetProfile() { localStorage.removeItem(KEY) }
